### ISSUE TITLE
multiprocessing.pool.MaybeEncodingError: Error sending result:

### ISSUE THREAD

**Issue by ghost** [gwct/referee#6]
Hello, 

encountering this error 
```

+ Making tmp directory: referee-tmpdir-04-10-2020.11-23-18-rYrIwO
Traceback (most recent call last):
  File "./referee-1.1.21/referee.py", line 110, in <module>
    referee(files, globs, step_start_time);
  File "./referee-1.1.21/referee.py", line 51, in referee
    for result in pool.imap(RC.getSubPID, range(globs['num-procs'])):
  File "/usr/lib/python2.7/multiprocessing/pool.py", line 673, in next
    raise value
multiprocessing.pool.MaybeEncodingError: Error sending result: 'psutil.Process(pid=8172, name='referee.py', started='11:29:58')'. Reason: 'TypeError("can't pickle thread.lock objects",)'

```

The command used was
```

/referee-1.1.21/referee.py -gl reads-gl.glf.gz -ref ref.fasta --fastq --correct -o reference -p 20
```
On Ubuntu 18.04 

thank you

**Comment by ghost** [comment]
Ok it came from my python install, not from referee

**Comment by ghost** [comment]
I was too fast, I am getting the error again, so it's not the python install actually.

**Comment by gwct** [comment]
Hello,
Can you try running with `--quiet` set? It seems to be having a problem passing info to psutil, which is used for tracking progress, and `--quiet` should prevent that from happening. Let me know if that runs or throws an error.

**Comment by ghost** [comment]
In the meantime I could run it successfully with a single thread.

**Comment by gwct** [comment]
That's great! Did --quiet throw the same error when specifying multiple threads? Will that be a single thread be sufficient for your purposes? If not, you could send me a snippet of your input file so I can try and replicate the issue to try and fix.

**Comment by ghost** [comment]
I haven't tried with --quiet. However, a single thread was sufficient for my purpose, hopefully I work with little genomes ^^'

**Comment by gwct** [comment]
Ok, let me know if this becomes a problem. I'm going to close this for now since I can't replicate it. The parallelization of Referee will be completely updated soon as well. See [Issue #3](https://github.com/gwct/referee/issues/3) for more info.
